### ISSUE TITLE
Crash just like with the Reforked version

### ISSUE THREAD

**Issue by MarfMaster** [MCTeamPotato/Better-End-Potato-Edition#8] opened 2023-03-09 09:08 UTC
I've got a modpack that crashes on entering any world only when this mod is enabled.
[crash-2023-03-09_09.58.25-client.txt](https://github.com/MCTeamPotato/Better-End-Potato-Edition/files/10929682/crash-2023-03-09_09.58.25-client.txt)

**Comment by Kasualix** [comment] 2023-03-10 09:44
Can you try [this version](https://github.com/MCTeamPotato/Better-End-Potato-Edition/actions/runs/4383232144)?

Besides, there are far too many mods to realistically narrow down the issue. It would be great if you could determine the minimum set of mods necessary to reproduce this (as it seems to be a specific incompatibility with one of your mods).

**Comment by Kasualix** [comment] 2023-03-25 13:30
Since I have not received any response from you, I will close this issue now. If you need further assistance, please feel free to reopen the issue and reply.

**Closed by Kasualix** 2023-03-25 13:30 UTC
Labels: need-more-info
